services:
  hivemq:
    image: hivemq/hivemq4
    container_name: hivemq
    ports:
      - "15672:8080"  # HiveMQ Web UI port
      - "8000:8000"  # HiveMQ WebSocket port
      - "1883:1883"  # MQTT port
    ulimits:
      nofile:
        soft: 500000
        hard: 500000
    networks:
      - smaiax-backend-network
      - smaiax-iot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]  # Simple check for HiveMQ Web UI
      interval: 10s
      timeout: 5s
      retries: 5

  data_generator:
    build: .
    container_name: data_generator
    depends_on:
      hivemq:
        condition: service_healthy
    environment:
      - SMART_METER_ID=${SMART_METER_ID:-}
      - MQTT_BROKER_HOST=hivemq
      - MQTT_PORT=1883
      - TIME_INTERVAL=5
    links:
      - hivemq
    networks:
      - smaiax-iot-network

networks:
  smaiax-backend-network:
    name: "smaiax-backend-network"
    driver: bridge
  smaiax-iot-network:
    name: "smaiax-iot-network"
    driver: bridge